### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by ghost** [rodrigopedra/laravel-clearsale-id#2]
- Version: 1.0.0
- PHP: 7.2.33

### Description

This issue is related to its parent library issue rodrigopedra/clearsale-id#3

**Comment by rodrigopedra** [comment]
Closed by https://github.com/rodrigopedra/laravel-clearsale-id/commit/70f5f62b020988fe2bf69ce68750c32d172087dd
